pipeline {
  agent none

  stages {

    stage('Back-end') {
      agent { docker { image 'maven:3.8.1-adoptopenjdk-11' } }
      steps {
        sh 'mvn --version'
      }
    }

    stage('Front-end') {
      agent { docker { image 'node:16-alpine' } }
      steps {
        sh 'node --version'
      }
    }

    stage('Run Docker Container') {
  agent { label 'any' }   // or 'master' or another label that exists
  steps {
    script {
      sh "docker rm -f my-nginx || true"
      sh "docker pull nginx:latest"
      sh '''
        docker run -d --name my-nginx -p 8080:80 nginx:latest
      '''
    }
  }
}
  }
}
  
