pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
     stage('Run Docker Container') {
      agent { label 'docker' }   // <--- ensure you have a node labeled 'docker'
      steps {
        script {
          echo "Running Docker container..."

          sh "docker rm -f my-nginx || true"
          sh "docker pull nginx:latest"

          sh '''
            docker run -d \
              --name my-nginx \
              -p 8080:80 \
              nginx:latest
          '''

          echo "Container started at http://<YOUR-SERVER-IP>:8080"
        }
      }
    }
  }
}
