pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Run Docker Container') {
      agent {
        docker { image 'docker pull nginx:latest' }
            steps {
                script {
                    echo "Running Docker container..."

                    // // pull image
                    // sh "docker pull nginx:latest"

                    // remove existing container if running
                    sh "docker rm -f my-nginx || true"

                    // run the container
                    sh """
                        docker run -d \
                        --name my-nginx \
                        -p 8080:80 \
                        nginx:latest
                    """

                    echo "Container started at http://<YOUR-SERVER-IP>:8080"
                }
            }
    }
  }
}
